BUG-13235 Multiple improvements to init.d scripts
Ensure proper pid directory. Improved descriptions. Ensure that status, start,
stop and restart work on via both debs and rpms (ubuntu and centos, respectively).
Remove usage of jps in favor of pidofproc. Better usage of lsb logging functions.

diff --git a/assemble/scripts/init.d/accumulo-tserver b/assemble/scripts/init.d/accumulo-tserver
--- a/assemble/scripts/init.d/accumulo-tserver
+++ b/assemble/scripts/init.d/accumulo-tserver
@@ -7,7 +7,7 @@
 # Default-Start:    2 3 4 5
 # Default-Stop:     0 1 6
 # Short-Description: accumulo tserver and logger processes
-# Description:      The accumulo tserver process for accumulo
+# Description:      The Accumulo TServer process hosts data
 ### END INIT INFO
 
 # Licensed to the Apache Software Foundation (ASF) under one or more
@@ -26,18 +26,23 @@
 # limitations under the License.
 
 # Do NOT "set -e"
-install -d -m 0775 -o root -g accumulo /var/run/accumulo
+install -d -m 0755 -o accumulo -g accumulo /var/run/accumulo
 
 # PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/lib/accumulo/bin
-DESC="Accumulo Tserver"
+DESC="Accumulo TServer"
 NAME=accumulo-tserver
 ACCUMULO_PROC=tserver
 DAEMON=/usr/lib/accumulo/bin/start-server.sh
 IP=`ifconfig | grep inet[^6] | awk '{print $2}' | sed 's/addr://' | grep -v 0.0.0.0 | grep -v 127.0.0.1 | head -n 1`
-DAEMON_ARGS="$IP slaves"
-PIDFILE=/var/run/$NAME.pid
+DAEMON_ARGS="$IP tserver \"tablet server\""
+PIDFILE=/var/run/accumulo/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
+
+STATUS_RUNNING=0
+STATUS_DEAD=1
+STATUS_NOT_RUNNING=3
+STATUS_NOT_RUNNING_DEB=4
 
 # Read configuration variable file if it is present
 [ -r /etc/default/accumulo ] && . /etc/default/accumulo
@@ -66,13 +71,24 @@ do_start()
 	#  0 if daemon has been started
 	#  1 if daemon was already running
 	#  2 if daemon could not be started
-	
-  if [ "`jps -m | grep $ACCUMULO_PROC`" ] ; then return 1; fi
 
-  su -s /bin/sh $TARGET_USER -c "/usr/lib/accumulo/bin/start-server.sh $IP tserver \"tablet server\""
+    PID=$(check_status_of_proc)
+    RETVAL=$?
+    if [ "$RETVAL" -eq "0" ] ; then return 1; fi
 
-  if [ "`jps -m | grep $ACCUMULO_PROC`" ] ; then return 0; fi
-	return 2
+    # Export PIDFILE so accumulo scripts will know where to write the pid to
+    export PIDFILE
+
+    su -s /bin/sh $TARGET_USER -c "$DAEMON $DAEMON_ARGS > /dev/null || return 1"
+
+    PID=$(check_status_of_proc)
+    if [ -z "$PID" ]; then
+        log_warning_msg "Could not determine pid for ${DESC}"
+        return 2
+    fi
+
+    return 0
+
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
@@ -90,73 +106,137 @@ do_stop()
 	#  1 if daemon was already stopped
 	#  2 if daemon could not be stopped
 	#  other if a failure occurred
+    
+    # Get the pid
+    PID=$(check_status_of_proc)
+    RETVAL=$?
 
-  if [ ! "`jps -m | grep $ACCUMULO_PROC`" ] ; then return 1; fi
+    # If we got non-zero result, it's already dead
+    if [ $RETVAL -ne '0' ] ; then return 1; fi
 
-	su -s /bin/sh $TARGET_USER -c "/usr/lib/accumulo/bin/accumulo admin stop $IP"
+    # stop the process
+	su -s /bin/sh $TARGET_USER -c "/usr/lib/accumulo/bin/accumulo admin stop $IP" > /dev/null
 
-  if [ "`jps -m | grep $ACCUMULO_PROC`" ] ; then jps -m | grep $ACCUMULO_PROC | awk '{print $1}' | xargs kill -9; fi
+    # make sure the process died but don't just blindly sleep
+    for i in `seq 1 5`; do
+        ps $PID > /dev/null
+        RETVAL=$?
+        if [ $RETVAL -ne "0" ] ; then rm $PIDFILE; return 0; fi
+        sleep 1
+    done
 
-  if [ "`jps -m | grep $ACCUMULO_PROC`" ] ; then return 2; fi
-	return 0;
+    log_warning_msg "${DESC} did not cleanly stop. Killing..."
+
+    # try kill and repeat check
+    kill -9 $PID
+
+    # make sure the process died but don't just blindly sleep
+    for i in `seq 1 5`; do
+        ps $PID > /dev/null
+        RETVAL=$?
+        if [ $RETVAL -ne "0" ] ; then rm $PIDFILE; return 0; fi
+        sleep 1
+    done
+
+    return 2;
+}
+
+check_status_of_proc() {
+    pidofproc -p $PIDFILE $PROC_NAME
+}
+
+check_status() {
+    PID=$(check_status_of_proc)
+    status=$?
+
+    case "$status" in
+        $STATUS_RUNNING)
+            log_success_msg "${DESC} is running"
+            ;;
+        $STATUS_DEAD)
+            log_failure_msg "${DESC} is dead and pid file exists"
+            ;;
+        $STATUS_NOT_RUNNING|$STATUS_NOT_RUNNING_DEB)
+            log_success_msg "${DESC} is not running"
+            ;;
+        *)
+            log_failure_msg "${DESC} status is unknown"
+            ;;
+    esac
+    return $status
 }
 
 case "$1" in
-  start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  status)
-      status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-      ;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
-  restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
-  *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
-esac
+    start)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC"
+        do_start
+        case "$?" in
+            0) 
+                [ "$VERBOSE" != no ] && log_end_msg 0 
+                log_success_msg "${DESC} was started"
+                ;;
+            1)
+                [ "$VERBOSE" != no ] && log_end_msg 0 
+                log_warning_msg "${DESC} already running as $(check_status_of_proc)"
+                ;;
+            2)
+                [ "$VERBOSE" != no ] && log_end_msg 1
+                log_failure_msg "${DESC} could not be started"
+                ;;
+        esac
+        ;;
+    stop)
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC"
+        do_stop
+        case "$?" in
+            0)
+                log_success_msg "${DESC} was stopped"
+                ;;
+            1) 
+                [ "$VERBOSE" != no ] && log_end_msg 0
+                log_warning_msg "${DESC} was already stopped"
+                ;;
+            2)
+                [ "$VERBOSE" != no ] && log_end_msg 1
+                log_failure_msg "${DESC} could not be stopped"
+                ;;
+        esac
+        ;;
+    status)
+        check_status && exit 0 || exit $?
+        ;;
+    restart)
+        do_stop
+        log_success_msg "${DESC} was stopped"
+        case "$?" in
+            0|1)
+                do_start
+                case "$?" in
+                    0) 
+                        log_end_msg 0 
+                        log_success_msg "${DESC} was started"
+                        ;;
+                    1) 
+                        log_end_msg 1
+                        log_failure_msg "${DESC} failed to restart"
+                        ;; # Old process is still running
+                    *) 
+                        log_end_msg 1
+                        log_failure_msg "${DESC} failed to start"
+                        ;; # Failed to start
+                esac
+                ;;
+            *)
+                # Failed to stop
+                log_end_msg 1
+                log_failure_msg "${DESC} failed to stop"
+                ;;
+        esac
+        ;;
+    *)
+        echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
+        exit 3
+        ;;
+    esac
 
 :
